# Generated by Django 5.0.2 on 2024-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('person', models.CharField(max_length=100)),
                ('night_work', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_morning', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('normal_working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_evening', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('work_nights', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('work_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
