# Generated by Django 5.0.2 on 2024-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='night_work',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='normal_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='overtime_evening',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='overtime_morning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_nights',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
