# Generated by Django 5.0.2 on 2024-02-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0002_alter_workrecord_night_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrecord',
            old_name='work_deduction',
            new_name='work_deduction_evening',
        ),
        migrations.AddField(
            model_name='workrecord',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='work_deduction_morning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
