# Generated by Django 5.0.2 on 2024-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0003_rename_work_deduction_workrecord_work_deduction_evening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('A', 'غایب'), ('P', 'حاضر')], default='P', max_length=10),
        ),
    ]
