# Generated by Django 5.0.2 on 2024-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0004_workrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='arrived_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
