# Generated by Django 5.0.2 on 2024-02-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0005_alter_workrecord_arrived_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrecord',
            options={'ordering': ['date', 'person'], 'verbose_name': 'Work Record', 'verbose_name_plural': 'Work Records'},
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='arrived_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='night_work',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='normal_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='overtime_evening',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='overtime_morning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_deduction_evening',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_deduction_morning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='work_nights',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
