# Generated by Django 5.0.2 on 2024-02-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0007_alter_workrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
