# Generated by Django 5.0.2 on 2024-02-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0008_alter_workrecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecordFinally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('normal_working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('over_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('work_night', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('work_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('absent_overtime', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], default='P', max_length=10)),
            ],
        ),
    ]
