# Generated by Django 5.0.2 on 2024-02-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0009_workrecordfinally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecordfinally',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
