# Generated by Django 5.0.2 on 2024-02-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0010_alter_workrecordfinally_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecordfinally',
            name='absent_overtime',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='normal_working_hours',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='over_time',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='work_deduction',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='work_night',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, null=True),
        ),
    ]
