# Generated by Django 5.0.2 on 2024-02-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0011_alter_workrecordfinally_absent_overtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecordfinally',
            name='absent_overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='normal_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='over_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='work_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='work_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
