# Generated by Django 5.0.2 on 2024-02-17 06:10

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0012_alter_workrecordfinally_absent_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecordfinally',
            name='date_persian',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
    ]
