# Generated by Django 5.0.2 on 2024-02-17 06:17

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0013_workrecordfinally_date_persian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecordfinally',
            name='date_persian',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
