# Generated by Django 5.0.2 on 2024-02-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0015_alter_workrecordfinally_date_persian'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecordfinally',
            name='absent_overtime_formatted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workrecordfinally',
            name='normal_working_hours_formatted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workrecordfinally',
            name='over_time_formatted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workrecordfinally',
            name='work_deduction_formatted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workrecordfinally',
            name='work_night_formatted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
