# Generated by Django 5.0.2 on 2024-02-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0016_workrecordfinally_absent_overtime_formatted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_holiday', models.DateField()),
                ('event', models.CharField(max_length=200)),
            ],
        ),
    ]
