# Generated by Django 5.0.2 on 2024-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0017_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecordfinally',
            name='status_holiday',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
